<#
Anexo A, apartado A.4 · El ciclo completo: entrenar el adaptador y evaluar ensayo a ensayo.

Apunta el envoltorio local hacia la dirección temporal del servicio de inferencia de la GPU, de modo que el
cliente que recorre las sesiones pueda enviarle las peticiones.
#>

param(
    [Parameter(Mandatory = $true)]
    [string]$TunnelUrl,

    [int]$LocalPort = 18080
)

$ErrorActionPreference = "Stop"

$RepoRoot = Resolve-Path (Join-Path $PSScriptRoot "..")
$EnvDir = Join-Path $RepoRoot "infra\env"
$EnvFile = Join-Path $EnvDir "centaur.env.local"

New-Item -ItemType Directory -Force -Path $EnvDir | Out-Null
$GeneratedAtUtc = (Get-Date).ToUniversalTime().ToString("o")

$upstream = $TunnelUrl.Trim().TrimEnd("/")
if (-not $upstream.EndsWith("/generate")) {
    $upstream = "$upstream/generate"
}

$content = @"
# Local real Centaur configuration.
# Generated by ops/configure_centaur_colab_upstream.ps1.
# This configuration uses the local FastAPI wrapper as a stable endpoint
# and forwards real inference to the Colab Centaur backend.

CENTAUR_ENDPOINT=http://127.0.0.1:$LocalPort/generate
CENTAUR_MODEL_NAME=marcelbinz/Llama-3.1-Centaur-70B-adapter
CENTAUR_TIMEOUT_S=300
CENTAUR_ENV_GENERATED_AT_UTC=$GeneratedAtUtc

CENTAUR_SERVICE_BACKEND=upstream
CENTAUR_UPSTREAM_URL=$upstream
CENTAUR_UPSTREAM_TIMEOUT_S=300
CENTAUR_UPSTREAM_HEALTH_TIMEOUT_S=30

# Optional. Leave blank unless your upstream endpoint requires a bearer token.
CENTAUR_TOKEN=
HF_TOKEN=
CENTAUR_UPSTREAM_TOKEN=
"@

Set-Content -Path $EnvFile -Value $content -Encoding UTF8

Write-Output "configured_env=$EnvFile"
Write-Output "local_endpoint=http://127.0.0.1:$LocalPort/generate"
Write-Output "upstream_endpoint=$upstream"
Write-Output "next_start=powershell -ExecutionPolicy Bypass -File ops\start_centaur_service.ps1 -Port $LocalPort"
Write-Output "next_run=python examples\run_real_centaur_psych101_case.py --limit 2"
